Models/Book.cs
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string AuthorName { get; set; }
        public string Language  { get; set; }
        public string BookDetails { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace BookStore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AddController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    public class AddController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AddController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(Book obj)
        {
            _db.Books.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index","Home");
        }
        public IActionResult Edit(int ? id)
        {
            if(id == null || id <= 0)
            {
                return NotFound();
            }
            var book = _db.Books.Find(id);
            if(book == null)return NotFound();

            return View(book);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Book obj)
        {
            
            _db.Books.Update(obj);
            _db.SaveChanges();

            return RedirectToAction("Index","Home");
        }
        public IActionResult Details(int? id)
        {
            if (id == null || id <= 0)
            {
                return NotFound();
            }
            var book = _db.Books.Find(id);
            if (book == null) return NotFound();
           ViewBag.Book = book;
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id <= 0)
            {
                return NotFound();
            }
            var book = _db.Books.Find(id);
            if (book == null) return NotFound();

            return View(book);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Book obj)
        {
            _db.Books.Remove(obj);
            _db.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/AuthorController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        private readonly ApplicationDbContext _db;
        public AuthorController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index(int ? id)
        {
            if(id == null|| id==0)
            {
                return NotFound();
            }
           var name=_db.Books.Find(id).AuthorName;
            var bookList= _db.Books.Where(x => x.AuthorName == name).ToList();
         
            return View(bookList);
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var name = _db.Books.Find(id);
            
        
            return View(name);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Book obj)
        {
            if (obj == null)
            {
                return NotFound();
            }
            var name = _db.Books.Find(obj.Id).AuthorName;
            var books=_db.Books.Where(x=>x.AuthorName == name).ToList();
            foreach (var book in books)
            {
                book.AuthorName=obj.AuthorName;
                //_db.Books.Update(book);
               
            }
            _db.Books.UpdateRange(books);
            _db.SaveChanges();
            return RedirectToAction("Index","Home");
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var name = _db.Books.Find(id);


            return View(name);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Book obj)
        {
            if (obj == null)
            {
                return NotFound();
            }
            var name = _db.Books.Find(obj.Id).AuthorName;
            var books = _db.Books.Where(x => x.AuthorName == name).ToList();
            foreach (var book in books)
            {
                book.AuthorName = obj.AuthorName;
                //_db.Books.Update(book);

            }
            _db.Books.RemoveRange(books);
            _db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/HomeController.cs
using BookStore.Data;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HomeController(ApplicationDbContext db)
        {
            _db = db;
        }
 
        public IActionResult Index()
        {
            IEnumerable<Book> bookList=_db.Books;
            return View(bookList);
        }
        public IActionResult Add()
        {
            
            return View();
        }
        //post method
        [HttpPost]
        [IgnoreAntiforgeryToken]
        public IActionResult Index(Book book)
        {
            _db.Books.Add(book);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Add/Add.cshtml
@model Book
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2 text-center">
            <h2 class="text-primary">Add a new book</h2>
            <hr />

        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class=" form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="AuthorName"></label>
            <input asp-for="AuthorName" class=" form-control" />
            <span asp-validation-for="AuthorName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Language"></label>
            <input asp-for="Language" class=" form-control" />
            <span asp-validation-for="Language" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BookDetails"></label>
            <input asp-for="BookDetails" class=" form-control" />
            <span asp-validation-for="BookDetails" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">Back to Home</a>
    </div>
</form>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Add/Delete.cshtml
@model Book
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2 text-center">
            <h2 class="text-primary">Delete this Book</h2>
            <hr />

        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name"  disabled class=" form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="AuthorName"></label>
            <input asp-for="AuthorName" disabled class=" form-control" />
            <span asp-validation-for="AuthorName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Language"></label>
            <input asp-for="Language" disabled class=" form-control" />
            <span asp-validation-for="Language" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BookDetails"></label>
            <input asp-for="BookDetails" disabled class=" form-control" />
            <span asp-validation-for="BookDetails" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">Back to Home</a>
    </div>
</form>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Add/Details.cshtml
@model Book
<div class="border p-3 mt-4">
    <div class="row pb-2 text-center">
        <h2 class="text-primary">Book Details</h2>
        <hr />
        
    </div>

   
    <table>
        <td>
            <div class="w-75 btn-group" role="group">
                 <a asp-controller="Add" asp-action="Edit" asp-route-id="@ViewBag.Book.Id" style="white-space: nowrap;">
                 <h3 class="text text-primary ">Update</h3>
                 </a>
                <a asp-controller="Add" asp-action="Delete" asp-route-id="@ViewBag.Book.Id" style="padding-left:10px">
                    <h3 class="text text-primary ">Delete</h3>
                </a>

            </div>
        </td>
       
    </table>
    <table>
        <tbody>
            <tr>
                <td>
                    <h5>Book Name : @ViewBag.Book.Name</h5>
                </td>
            </tr>
            <tr>
                <td>
                    <h5>Book Author : @ViewBag.Book.AuthorName</h5>
                </td>
            </tr>
            <tr>
                <td>
                    <h5>Book Language : @ViewBag.Book.Language</h5>
                </td>
            </tr>
            <tr>
                <td>
                    <h5>Book Details : @ViewBag.Book.BookDetails</h5>
                </td>
            </tr>
        
        </tbody>
    </table>
 </div>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Add/Edit.cshtml
@model Book
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2 text-center">
            <h2 class="text-primary">Edit book</h2>
            <hr />

        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class=" form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="AuthorName"></label>
            <input asp-for="AuthorName" class=" form-control" />
            <span asp-validation-for="AuthorName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Language"></label>
            <input asp-for="Language" class=" form-control" />
            <span asp-validation-for="Language" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BookDetails"></label>
            <input asp-for="BookDetails" class=" form-control" />
            <span asp-validation-for="BookDetails" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">Back to Home</a>
    </div>
</form>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/AddBook/Index.cshtml
@model Book
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2 text-center">
            <h2 class="text-primary">Add a new book</h2>
            <hr />

        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class=" form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="AuthorName"></label>
            <input asp-for="AuthorName" class=" form-control"/>
            <span asp-validation-for="AuthorName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Language"></label>
            <input asp-for="Language" class=" form-control" />
            <span asp-validation-for="Language" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BookDetails"></label>
            <input asp-for="BookDetails" class=" form-control" />
            <span asp-validation-for="BookDetails" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">Back to Home</a>
    </div>
</form>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Author/Delete.cshtml
@model Book
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2 text-center">
            <h2 class="text-primary">Deleting Author</h2>
            <hr />

        </div>


        <div class="mb-3" >
            <label asp-for="AuthorName"></label>
            <input asp-for="AuthorName" disabled class=" form-control" />
            <span asp-validation-for="AuthorName" class="text-danger"></span>
        </div>


        <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">Back to Home</a>
        </div>
</form>

Views/Author/Edit.cshtml
@model Book
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2 text-center">
            <h2 class="text-primary">Update Author Details</h2>
            <hr />

        </div>
        <div class="mb-3" hidden>
            <label asp-for="Name" hidden></label>
            <input asp-for="Name" hidden class=" form-control" />
            <span asp-validation-for="Name" hidden class="text-danger"></span>
        </div>

        <div class="mb-3" >
            <label asp-for="AuthorName"></label>
            <input asp-for="AuthorName" class=" form-control" />
            <span asp-validation-for="AuthorName" class="text-danger"></span>
        </div>

        <div class="mb-3" hidden>
            <label asp-for="Language"></label>
            <input asp-for="Language" class=" form-control" />
            <span asp-validation-for="Language" class="text-danger"></span>
        </div>
        <div class="mb-3" hidden>
            <label asp-for="BookDetails"></label>
            <input asp-for="BookDetails" class=" form-control" />
            <span asp-validation-for="BookDetails" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">Back to Home</a>
        </div>
</form>

Views/Author/Index.cshtml
@model List<Book>
@{
    ViewData["Title"] = "Index";
}
@{
    var firstName = Model.FirstOrDefault().AuthorName;
    if (firstName == null) firstName = "Unknown Author";

}
<h2>@firstName's  Book List</h2>
<hr />
<table class="text-end " style="width:100%">
    <td>
        <div class=" btn-group" role="group">
            <a asp-controller="Author" asp-action="Edit" asp-route-id="@Model[0].Id "style="white-space: nowrap;">
                <h3 class="text text-primary ">Update</h3>
            </a>
            <a asp-controller="Author" asp-action="Delete" asp-route-id="@Model[0].Id" style="padding-left:10px">
                <h3 class="text text-primary ">Delete</h3>
            </a>

        </div>
    </td>

</table>
@if (Model.Any())
{
    <table>
        <thead>
            <tr>
                <th style="width:100px">Book ID</th>
                <th>Book Name</th>
               
            </tr>
        </thead>
        <tbody>
            @foreach (var book in Model)
            {
                <tr>
                    <td>@book.Id</td>
                    <td>@book.Name</td>
                    @*<td>@book.PublishDate.ToShortDateString()</td>*@
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>No books found for this author.</p>
}

Views/Home/Add.cshtml
@model Book
<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2 text-center">
            <h2 class="text-primary">Add a new book</h2>
            <hr />

        </div>
        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class=" form-control"/>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="AuthorName"></label>
            <input asp-for="AuthorName" class=" form-control"/>
            <span asp-validation-for="AuthorName" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Language"></label>
            <input asp-for="Language" class=" form-control" />
            <span asp-validation-for="Language" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="BookDetails"></label>
            <input asp-for="BookDetails" class=" form-control" />
            <span asp-validation-for="BookDetails" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary" style="width:150px">Back to Home</a>
    </div>
</form>
@section Scripts
    {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}

Views/Home/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "Home Page";
}

<h1> All Book List</h1>

<table class=" table table-bordered table-striped" style="width:100%">

    <thead>
        <tr>
            <th>
                Book Name
            </th>
            <th>
                Author Name
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {
            <tr>
                <td width="50%">
                   <a asp-controller="Add" asp-action="Details" asp-route-id="@obj.Id">
                        @obj.Name
                   </a> 
                </td>
                <td width="30%"> 
                     <a asp-controller="Author" asp-action="Index" asp-route-id="@obj.Id">
                    @obj.AuthorName

                    </a>
                </td>

            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Add" asp-action="Add">Add Book</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>